name: 'Greeting Message'
description: 'Post an initial message when a PR is opened'
inputs:
  repo-token: 
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  pr-message:
    description: 'Comment to post upon opening a pull request'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'